### ISSUE TITLE
Wildcard Environments to Pattern

### ISSUE THREAD

**Issue by dmhalejr** [tomzo/gocd-yaml-config-plugin#108]
Is it within the realm of possibility to have wildcarded pipeline patterns for environments? 

So instead of:
```
environments:
   test:
     pipelines:
       - one-int
       - one-uat
       - one-prod
```

We could do:
```
environments:
   test:
     pipelines:
       - one*
```

Loving the plugin! Thanks for all you do!
