### ISSUE TITLE
Schema validation while importing pipeline configuration

### ISSUE THREAD

**Issue by sheroy** [tomzo/gocd-yaml-config-plugin#113]
Currently the yaml config plugin doesn't have a mechanism to validate the schema of the YAML pipeline configuration. There is no indication of errors in YAML configuration due to non-conformance to the GoCD pipeline schema. 

Example:

```
pipelines:
  pipe1:
    group: simple
    materials:
      mygit: 
        git: <Some URL>
    stages:
      - build: # name of stage
          elastic_profile_id: demo-app
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
command: echo "hello world"
```   
This configuration should have thrown an error because the elastic_profile_id element is in the wrong location. Currently, there is no error or warning displayed anywhere to indicate something was misconfigured.
