### ISSUE TITLE
Can a stage skip external artifact if the job fails?

### ISSUE THREAD

**Issue by davified** [tomzo/gocd-yaml-config-plugin#116]
Hi there,

First of all, thank you for creating this yaml plugin :-)

I have a question. I'm specifying an external artifact in my pipeline, and for some reason it tries to push the artifact to my artifact repository even if the job failed. Is this the expected behaviour? If it is, is there any way to skip external artifacting if the job fails?

Here's my pipeline:
```yaml
#pipeline.gocd.yaml
pipelines:
  demo_ci_pipeline:
    group: demo_group
    materials:
      demo_git:
        git: https://github.com/some/project
    stages:
      - commit:
          clean_workspace: true
          jobs:
            build_and_test:
              elastic_profile_id: demo-app
              tasks:
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - bin/build.sh
              - exec:
                  command: bash
                  arguments:
                  - -c
                  - bin/test.sh
              artifacts:
              - external:
                  id: docker-release-candidate
                  store_id: dockerhub
                  configuration:
                    options:
                      Image: my-username/my-app
                      Tag: v${GO_PIPELINE_LABEL}
```

Thank you!
