### ISSUE TITLE
Publish only when the tags are pushed

### ISSUE THREAD

**Issue by pritibiyani** [tomzo/gocd-yaml-config-plugin#117]
- Does GO/CD has a support to get triggered on tags push?
- We want to publish an npm package only when a tag is pushed and not every time. We can make it manual trigger, but trying to automate. 

Something like follow: 
```
// .travis.yml
language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: dungnq@itbox4vn.com
  api_key:
    secure: BSjy5UrLZOgrTnaA...
  on:
    branch: master
    **tags: true**
```
Let me know if there is any other way to approach this one. 

Thanks.
