### ISSUE TITLE
how to get a dynamic value (${GO_VERSION}) evaluated in the yml for a task

### ISSUE THREAD

**Issue by sanjusoftware** [tomzo/gocd-yaml-config-plugin#12]
I have a bash command in my gocd.yaml file, like following:
```yaml
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker build --no-cache -t 10.191.60.17:5000/mck/solr_collection_deployer:latest -t 10.191.60.17:5000/mck/solr_collection_deployer:${GO_REVISION} ."
```

`${GO_REVISION}` worked just fine when its right there in the XML config, however, when I took it out in YML template and created the pipeline using the above snippet (ignoring the code above and below it), the `${GO_REVISION}` doesn't seem to get evaluated...

what am I doing wrong? any help would be much appriciated

**Comment by tomzo** [comment]
Hi,

So probably the reason is this - in XML you had no name for the (only?) material in your pipeline. But now I suspect you have something like this in yaml:
```yaml
mygit:
  type: git
  url: http://example.com/mygit.git
```

This would have caused Go to no longer set `GO_REVISION` environment variable. Instead now it is setting something like `GO_REVISION_MYGIT`. Look at you build log.
I might be wrong though, so perhaps post it here.
