### ISSUE TITLE
Job failed with timeout zero

### ISSUE THREAD

**Issue by Raviadonis** [tomzo/gocd-yaml-config-plugin#120]
We are using Gocd version 17.2.0 and yaml-config-plugin version 0.7.0. While executing the pipeline, its ended-up with the below failure even thought we set the timeout value to `100` in the yaml file.

```
[go] Start to execute task: <exec command="/bin/bash" timeout="0" >
<arg>-c</arg>
<arg>cd test</arg>
</exec>.
[go] Current job status: failed.
```

YAML config:
```
    stages:
    - plan:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: true
        approval:
          type: manual
        jobs:
          terraform:
            timeout: 100
            artifacts:
            - build:
                source: '**/apply.tfplan'
            tasks:
            - exec:
                command: /bin/bash
                arguments:
                - -c
                - cd $TF_ROOT
                run_if: passed
            - exec:
                command: /bin/bash
                arguments:
                - -c
                - cd $TF_ROOT
                run_if: passed
```
