### ISSUE TITLE
Plugin material is not pushing auto_update attribute

### ISSUE THREAD

**Issue by ghost** [tomzo/gocd-yaml-config-plugin#122]
I'm trying to configure webhook notifications for GoCD. Unfortunately, they work only when a material is not configured with polling `auto_update: false`. Everything works for regular git material, but when I try to configure `github-pr` or `github-fb` materials - it seems this attribute is not propagated to GoCD.

Steps to reproduce:
Create a pipeline with github-pr metrial
```
    materials:
      repo-pr:
        plugin_configuration:
          id: github.pr
          version: 1
        options:
          url: git@github.com:organization/repo.git
        auto_update: false
        destination: repo
```
Try to trigger this material via Api
```
curl 'https://ci.example.com/go/api/material/notify/scm' \
      -u 'user:pass' \
      -H 'Confirm: true' \
      -X POST \
      -d "scm_name=repo-pr"
```
Response: 
```
Unable to find material. Materials must be configured not to poll for new changes before they can be used with the notification mechanism.
```

When I do the same via UI and unselect poll for changes. I can trigger material with the same request

Interesting note. When doing inverse transformaiton (exporting pipeline config to yaml) - `auto_update` field is missing.
