### ISSUE TITLE
SCM created by plugin does not set all environment variables

### ISSUE THREAD

**Issue by liaodaniel** [tomzo/gocd-yaml-config-plugin#125]
I'm using the yaml plugin with `plugin_configuration` and the github.pr plugin. What I notice is that some environment variables aren't set as opposed to using scm references in material. 

Are there any plans to support this behaviour?

## Setup
A sample of the pipeline yaml config:
```
    materials:
      jenkins_lab:
        plugin_configuration:
          id: github.pr
          version: 1
        options:
          url: git@github.com:liaodaniel/jenkins_lab.git
        destination: jenkins_lab
```
## Output
When a build is triggered with SCM material defined by the plugin config, only the following environment variables are set:
[go] setting environment variable 'GO_SCM_JENKINS_LAB_LABEL' to value '62110ee992a867e1fe910497ad0bdc40824bbcaf'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_URL' to value 'git@github.com:liaodaniel/jenkins_lab.git'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_ID' to value 'master'

## Expected Output
When a build is triggered with SCM material defined outside the plugin, additional environment variables are set:
[go] setting environment variable 'GO_SCM_JENKINS_LAB_LABEL' to value 'd9874c2f75b59476b66181e4d11c09e81ac4273c'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_URL' to value 'git@github.com:liaodaniel/jenkins_lab.git'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_TITLE' to value 'Foobar'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_URL' to value 'https://github.com/liaodaniel/jenkins_lab/pull/1'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_AUTHOR_EMAIL' to value '<email>'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_DESCRIPTION' to value ''
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_ID' to value '1'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_BRANCH' to value 'liaodaniel:foobar'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_PR_AUTHOR' to value 'Daniel Liao'
[go] setting environment variable 'GO_SCM_JENKINS_LAB_TARGET_BRANCH' to value 'liaodaniel:master'
