### ISSUE TITLE
how to use a file as an artifact?

### ISSUE THREAD

**Issue by sanjusoftware** [tomzo/gocd-yaml-config-plugin#13]
Here's the scenario:

I have a pipeline which generates an artifact 'image_ref' like following:

```yaml
pipelines:
  build-solr-collection-deployer-image1: # definition of mypipe1 pipeline
    group: APISolrCollectionDeployer
    materials:
      mygit: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: http://githuben.intranet.mckinsey.com/Enterprise-Architecture/solr_collection_deployer.git
        branch: master
    stages: # list of stages in order
      - build-image: # name of stage
          clean_workspace: true
          jobs:
            build-image: # name of the job
              artifacts:
               - build:
                   source: image_ref
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker build --no-cache -t x.x.x.x:5000/mck/solr_collection_deployer:latest -t x.x.x.x:5000/mck/solr_collection_deployer:${GO_REVISION_MYGIT} ."
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker push x.x.x.x:5000/mck/solr_collection_deployer:latest"
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker push x.x.x.x:5000/mck/solr_collection_deployer:${GO_REVISION_MYGIT}"
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "echo \"x.x.x.x:5000/mck/solr_collection_deployer:${GO_REVISION_MYGIT}\" | tee image_ref"
```

I use this artifact within another pipeline like following:

```yaml
pipelines:
  geo-offices-api-sandbox1:
    group: APIGeoOfficesSolrCollection
    materials:
      upstream:
        type: dependency
        pipeline: build-solr-collection-deployer-image
        stage: build-image
      mygit: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: http://githuben.intranet.mckinsey.com/Enterprise-Architecture/geo_offices_solr_collection.git
        branch: master
    stages: # list of stages in order
      - deploy: # name of stage
          clean_workspace: true
          jobs:
            deploy-solr-collection: # name of the job
              tasks:
               - fetch: # indicates type of task
                   pipeline: build-solr-collection-deployer-image
                   source: image_ref
                   stage: build-image
                   job: build-image
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker run -e HOST=sandbox -e COLLECTION=geo_offices -e GIT_REPO=http://githuben.intranet.mckinsey.com/Enterprise-Architecture/geo_offices_solr_collection.git `cat image_ref`"
```

however, the problem is that when go-server runs this build, it this to download this artifact as a "zip" file rather than a normal file. While I was doign the same in xml, it was working fine. The xml pipeline for the above is as below:

```xml
<pipelines group="APIGeoOfficesSolrCollection">
  <pipeline name="geo-offices-api-sandbox">
    <materials>
      <git url="http://githuben.intranet.mckinsey.com/Enterprise-Architecture/geo_offices_solr_collection.git" />
      <pipeline pipelineName="build-solr-collection-deployer-image" stageName="build-image" materialName="build-solr-collection-deployer-image" />
    </materials>
    <stage name="deploy">
      <jobs>
        <job name="deploy-solr-collection">
          <tasks>
            <fetchartifact pipeline="build-solr-collection-deployer-image" stage="build-image" job="build-image" srcfile="image_ref">
              <runif status="passed" />
            </fetchartifact>
            <exec command="bash">
              <arg>-c</arg>
              <arg>docker run -e HOST=sandbox -e COLLECTION=geo_offices -e GIT_REPO=http://githuben.intranet.mckinsey.com/Enterprise-Architecture/geo_offices_solr_collection.git `cat image_ref`</arg>
              <runif status="passed" />
            </exec>
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
</pipelines>
```

so, essentially the question is how do I specify that the source is just a file and not zip??

**Comment by tomzo** [comment]
You can specify that artifact to fetch is a file as documented [here](https://github.com/tomzo/gocd-yaml-config-plugin#fetch)
For you case that means, updating your fetch task definition to:
```yaml
...
               - fetch: # indicates type of task
                   pipeline: build-solr-collection-deployer-image
                   source: image_ref
                   is_file: yes
                   stage: build-image
                   job: build-image
...
```
