### ISSUE TITLE
doesn't support branchblacklist/branchwhitelist attribute for git-feature-branch plugin

### ISSUE THREAD

**Issue by MaoChhaya** [tomzo/gocd-yaml-config-plugin#131]
I am trying to use `git.fb` for trigger build multiple and specific branches, but it seems that the yaml-config-plugin does not support **_branchblacklist/branchwhitelist_** for `git.fb`. By default `git.fb` will be triggered any branch on github/gitlab but some branch is not already to trigger build

### configure
```
format_version: 5
pipelines:
  pipeline_name:
    group: pipeline_group
    label_template: "${git[:8]}"
    materials:
      git:
        plugin_configuration:
          id: git.fb
          version: 1
        options:
          url: some_url
```
**Is it possible to have branchblacklist/branchwhitelist attribute to filter branch?**

**Note**: I have tried to configure the `scms` tag in the cruise-config.xml to apply this issue but it is a bit complicated to configure `scms` global to get scm.id then back to configure `yaml-config `
