### ISSUE TITLE
Use pipeline parameters in the "approval" property

### ISSUE THREAD

**Issue by livanov** [tomzo/gocd-yaml-config-plugin#134]
I have 2 pipelines - `deploy-dev` and `deploy-prod`. I have setup parameters in my stages, thus both the pipelines use the same stage list anchor.

```
deploy-dev:
  group: dev
  parameters:
    namespace-name: "my-app-dev"
  materials:
    # ...
  stages: *deploy-stage-list
```

However, what I'd like is for the `deploy-prod` pipeline is that my 3rd (out of 5 stages) to be with `approval: manual`. The syntax doesn't allow me to use parameters for this. I am getting "approval should be hash or string" error.
