### ISSUE TITLE
Declaring a secret as an environement variable

### ISSUE THREAD

**Issue by yacinelazaar** [tomzo/gocd-yaml-config-plugin#136]
Hi,

I'm trying to figure out how to load a password from the bundled [file secret plugin](https://docs.gocd.org/current/configuration/secrets_management.html) from gocd into the yaml but so far no success.
Here is my approach:
```
environments:
  production:
    environment_variables:
      GIT_USER: yacine.laz
      GIT_PASSWORD: {{SECRET:[ci][git-password]}}
      REGISTRY_USER: yacine.laz
      REGISTRY_PASSWORD: "{{SECRET:[ci][registry-password]}}"
      REGISTRY: http://gitlab-registry
      REGISTRY_IMAGE: gitlab-registry.thinkpad.tld/yacine.laz/presentation-gitlab-k8s
    pipelines:
      - my-pipeline
pipelines:
  my-pipeline: # definition pipeline
    group: pipeline-group
    label_template: "${mygit[:8]}"
    locking: off
    materials:
      mygit:
        git: http://gitlab/yacine.laz/gocd-repo-test.git
        branch: master
        username: ${GIT_USER}
        password: ${GIT_PASSWORD}
...
```
According to gocd docs, I can reference the secret as an env variable or a parameter but I'm getting an error:
```
Error: pipeline.gocd.yml;
1. Line 5, column 19: Expected scalar, sequence, or mapping but found: mapping end
```

Does it need escaping or this simply does not work. If the latter, then what's the appropriate method to use password and secrets in the yml and be able to reference them.

**Comment by arvindsv** [comment]
Based on [this message](https://gitter.im/gocd/gocd?at=5e03fe278897197969fa6e4c), I believe this is not an issue. Is that right?

**Comment by yacinelazaar** [comment]
@arvindsv 
Yes Indeed, Damn the single quotes:
Would help if there was an example for those in the docs.

```
environments:
  production:
    environment_variables:
      REGISTRY_USER: yacine.laz
      REGISTRY_PASSWORD: '{{SECRET:[ci][registry-password]}}'
```

**Comment by arvindsv** [comment]
I don't have access to accept it, but I'm sure a PR to the docs will be accepted. :)

**Comment by yacinelazaar** [comment]
I will make some time for it in the weekend.

**Comment by dnewhook** [comment]
I got stung with referencing secrets in git materials today.  Based on the example above - this was how we solved the issue... (GOCD 20.4.0.
```
environments:
  production:
    environment_variables:
      GIT_USER: yacine.laz
      REGISTRY_USER: yacine.laz
      REGISTRY_PASSWORD: '{{SECRET:[ci][registry-password]}}'
      REGISTRY: http://gitlab-registry
      REGISTRY_IMAGE: gitlab-registry.thinkpad.tld/yacine.laz/presentation-gitlab-k8s
    pipelines:
      - my-pipeline
pipelines:
  my-pipeline: # definition pipeline
    group: pipeline-group
    label_template: "${mygit[:8]}"
    locking: off
    materials:
      mygit:
        git: http://gitlab/yacine.laz/gocd-repo-test.git
        branch: master
        username: ${GIT_USER}
        password: "{{SECRET:[ci][git-password]}}"
```

**Comment by Hraesvelg** [comment]
Hi, i tried same approach but : 

```
Failed to run git clone command STDERR: Cloning into '/var/lib/go-server/pipelines/flyweight/34a9441d-b292-4acf-8026-3698b38be053'...
STDERR: remote: Support for password authentication was removed on August 13, 2021.
STDERR: remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
STDERR: fatal: Authentication failed for '*.git'
```


```
pipelines:
    deploy_on_server:
        group: Default
        label_template: "##${COUNT}"
        lock_behavior: unlockWhenFinished
        display_order: 3
        materials:
            gocd_pipelines:
                git: *.git
                shallow_clone: true
                auto_update: true
                branch: main
                username: '{{SECRET:[scm-secret][scm-username]}}'
                password: '{{SECRET:[scm-secret][scm-password]}}'
```
