### ISSUE TITLE
how to add 2 'upstream' piplines as dependencies?

### ISSUE THREAD

**Issue by sanjusoftware** [tomzo/gocd-yaml-config-plugin#14]
I have the following pipelines created using gocd admin UI (which ran successfully):

```xml
<pipelines group="APIPersonSolrCollection">
  <pipeline name="persons-api-sandbox">
    <materials>
      <git url="http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection" />
      <pipeline pipelineName="build-solr-collection-deployer-image" stageName="build-image" materialName="build-solr-collection-deployer-image" />
    </materials>
    <stage name="deploy">
      <jobs>
        <job name="deploy-solr-collection">
          <tasks>
            <fetchartifact pipeline="build-solr-collection-deployer-image" stage="build-image" job="build-image" srcfile="image_ref">
              <runif status="passed" />
            </fetchartifact>
            <exec command="bash">
              <arg>-c</arg>
              <arg>docker run -e HOST=sandbox -e COLLECTION=api_persons -e GIT_REPO=http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection.git `cat image_ref`</arg>
              <runif status="passed" />
            </exec>
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
  <pipeline name="persons-api-development">
    <materials>
      <pipeline pipelineName="build-solr-collection-deployer-image" stageName="build-image" materialName="build-solr-collection-deployer-image" />
      <pipeline pipelineName="persons-api-sandbox" stageName="deploy" materialName="sandbox-deployment-successful" />
    </materials>
    <stage name="deploy">
      <jobs>
        <job name="deploy-solr-collection-to-dev-servers">
          <tasks>
            <fetchartifact pipeline="build-solr-collection-deployer-image" stage="build-image" job="build-image" srcfile="image_ref">
              <runif status="passed" />
            </fetchartifact>
            <exec command="bash">
              <arg>-c</arg>
              <arg>docker run -e HOST=development -e COLLECTION=api_persons -e GIT_REPO=http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection.git `cat image_ref`</arg>
              <runif status="passed" />
            </exec>
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
</pipelines>
```
while moving it to the github repo, I did the following YAML conversion:

```yaml
#ci.gocd.yaml
pipelines:
  persons-api-sandbox:
    group: APIPersonSolrCollection
    materials:
      upstream:
        type: dependency
        pipeline: build-solr-collection-deployer-image
        stage: build-image
      repo: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection.git
        branch: master
    stages: # list of stages in order
      - deploy: # name of stage
          clean_workspace: true
          jobs:
            deploy-solr-collection: # name of the job
              tasks:
               - fetch: # indicates type of task
                   pipeline: build-solr-collection-deployer-image
                   source: image_ref
                   stage: build-image
                   job: build-image
                   is_file: yes
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker run -e HOST=sandbox -e COLLECTION=api_persons -e GIT_REPO=http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection.git `cat image_ref`"
  persons-api-development:
    group: APIPersonSolrCollection
    materials:
      upstream:
        type: dependency
        pipeline: build-solr-collection-deployer-image
        stage: build-image
      upstream:
        type: dependency
        pipeline: persons-api-sandbox
        stage: deploy
    stages: # list of stages in order
      - deploy: # name of stage
          clean_workspace: true
          jobs:
            deploy-solr-collection-to-dev-servers: # name of the job
              tasks:
               - fetch: # indicates type of task
                   pipeline: build-solr-collection-deployer-image
                   source: image_ref
                   stage: build-image
                   job: build-image
                   is_file: yes
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker run -e HOST=development -e COLLECTION=api_persons -e GIT_REPO=http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection.git `cat image_ref`"
```

When GOCD runs this configuration, the first pipeline 'persons-api-sandbox' passes successfully however the second pipeline 'persons-api-development' fails with the following error.

```
1+ errors :: Pipeline "persons-api-development" tries to fetch artifact from pipeline "build-solr-collection-deployer-image" which is not an upstream pipeline;; - Config-Repo: http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection.git
```
FYI: in case you are wondering, 'build-solr-collection-deployer-image' pipeline already exists in another repo and is being used by other pipelines successfully. 

if I remove the second pipeline 'persons-api-sandbox' as dependency from 'persons-api-development' like below, then its all successful:

```yaml
  persons-api-development:
    group: APIPersonSolrCollection
    materials:
      upstream:
        type: dependency
        pipeline: build-solr-collection-deployer-image
        stage: build-image
    stages: # list of stages in order
      - deploy: # name of stage
          clean_workspace: true
          jobs:
            deploy-solr-collection-to-dev-servers: # name of the job
              tasks:
               - fetch: # indicates type of task
                   pipeline: build-solr-collection-deployer-image
                   source: image_ref
                   stage: build-image
                   job: build-image
                   is_file: yes
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "docker run -e HOST=development -e COLLECTION=api_persons -e GIT_REPO=http://githuben.intranet.mckinsey.com/Enterprise-Architecture/persons_solr_collection.git `cat image_ref`"
```

Am I doing it wrong? Essentially, I didn't find an easy way to define 2 pipelines as upstream dependencies under materials. Any help would be greatly appreciated!

**Comment by tomzo** [comment]
you have defined 2 materials with same name:
```yaml
      upstream:
        type: dependency
        pipeline: build-solr-collection-deployer-image
        stage: build-image
      upstream:
        type: dependency
        pipeline: persons-api-sandbox
        stage: deploy
```
see [here](https://github.com/tomzo/gocd-yaml-config-plugin#dependency) and a bug that this should have shown you a more sensible error #3
