### ISSUE TITLE
Environment variables from another one

### ISSUE THREAD

**Issue by Hraesvelg** [tomzo/gocd-yaml-config-plugin#206]
Hi every one !

Is possible to declare : 

```
pipelines:
    build_and_publish_image:
        environment_variables:
            PROJECT_NAME: "awesome_project"
...
        stages:
                jobs:
                        environment_variables:
                            NUM: 1
                            CUSTOM_NAME: "${PROJECT_NAME}-${NUM}"
```

i didn't found solution to do it... in my script where i use $CUSTOM_NAME the value is escape not evaluated in my script bash.
i have got "${PROJECT_NAME}-${NUM}" instead of "awesome_project-1"

thanks !
