### ISSUE TITLE
scm type not working

### ISSUE THREAD

**Issue by sgran** [tomzo/gocd-yaml-config-plugin#22]
Hi there,

I have this in my cruise-config.xml:
```
  <scms>
    <scm id="3ce0ae9a-003d-4af6-b055-49a5eb5b9e79" name="boat">
      <pluginConfiguration id="git.fb" version="1" />
      <configuration>
        <property>
          <key>url</key>
          <value>http://example.com/boatymcboatface.git</value>
        </property>
        <property>
          <key>branchwhitelist</key>
          <value>*</value>
        </property>
        <property>
          <key>branchblacklist</key>
          <value>master</value>
        </property>
      </configuration>
    </scm>
  </scms>
  <config-repos>
    <config-repo plugin="yaml.config.plugin">
      <git url=http://example.com/boatymcboatface.git" />
    </config-repo>
  </config-repos>
```

And then I have this in my pipeline.yaml:

```
pipelines:
  branchTest:
    group: basic
    locking: off
    materials:
      scm: "3ce0ae9a-003d-4af6-b055-49a5eb5b9e79"
      dest: app
    stages: # list of stages in order
      - build: # name of stage
          clean_workspace: true
          jobs:
            firstJob: # name of the job
              elastic_profile_id: tests
              tasks: # ordered list of tasks to execute in job csharp
               - exec: # indicates type of task
                   command: make
                   arguments:
                    - test
```

The only error I am getting is:
```
2017-01-31 14:48:54,080 ERROR [104@MessageListener for ConfigMaterialUpdater] GoRepoConfigDataSource:158 - Failed to parse configuration material http://example.com/boatymcboatface.git by Plugin yaml.config.plugin
```

the thing that makes me wonder if this is actually a defect is that the code appears to transform the scm material into scm_id with type set to plugin, while the go.cd docs suggest that:
```
    <materials>
      <scm ref="3ce0ae9a-003d-4af6-b055-49a5eb5b9e79" dest="dest">
      </scm>
    </materials>
```

Is the valid output.  Am I just doing it wrong, or is the code producing wrong configuration?

Cheers,

**Comment by tomzo** [comment]
Hi,

Firstly, this part is wrong:
```yaml
    materials:
      scm: "3ce0ae9a-003d-4af6-b055-49a5eb5b9e79"
      dest: app
```

Try make that into
```yaml
materials:
   myscm:
     scm_id:  "3ce0ae9a-003d-4af6-b055-49a5eb5b9e79"
     destination: app
```

`myscm` is any name you like. It is not required by GoCD but YAML syntax forces you to name your materials.

> the thing that makes me wonder if this is actually a defect is that the code appears to transform the scm material into scm_id with type set to plugin, while the go.cd docs suggest...

The plugin transforms YAML into JSON, whose *schema* is defined by configrepo extension point. It contains similar data to XML, but you should not get suggested by field names in XML. The JSON is modeled to resemble gocd API, not the xml.

BTW, the ultimate source of truth of what JSON is required to create scm material is this [class](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-access/src/com/thoughtworks/go/plugin/access/configrepo/contract/material/CRPluggableScmMaterial.java), which is deserialized with reflected type names. Something like this should be sent by plugin to server:
```json
{
  "scm_id": "3ce0ae9a-003d-4af6-b055-49a5eb5b9e79",
  "destination": "app",
  "name": "myscm",
  "type": "plugin"
}
```

Let me know if that helped
