### ISSUE TITLE
No error when 2 materials with the same names

### ISSUE THREAD

**Issue by xmik** [tomzo/gocd-yaml-config-plugin#3]
My pipeline depends on 2 upstream pipelines (P1 and P2) and 1 git repository. My config contains:

``` yaml
materials:
      git:
        git: "git@<path_to_git_project>.git"
        branch: ci
      upstream:
        pipeline: P1
        stage: test
      upstream:
        pipeline: P2
        stage: itest
```

It would be nice if there was an error saying that I configured 2 materials with the same name: `upstream`. Currently such configuration results in ignoring 1 upstream pipeline material.

**Comment by sanjusoftware** [comment]
the YAML file is read using com.esotericsoftware.yamlbeans.YamlReader in this plugin...  it automatically will override the value for a keyword with the last value found in the yaml. so e.g last material definition of 'upstream' in this issue. So, it'll load following:

```yaml
      upstream:
        pipeline: P2
        stage: itest
```

@tomzo I am thinking to fix this by introducing a YAML validator, but wanted to get your opinion as well on the approach. How do you think we can best handle this?
