### ISSUE TITLE
Support YAML aliases in dedicated section

### ISSUE THREAD

**Issue by sandro-h** [tomzo/gocd-yaml-config-plugin#32]
Hey there,

YAML supports aliases out of the box. See [these use cases](https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)) for example, and the spec [here](http://www.yaml.org/spec/1.2/spec.html#id2786196).

As this is supported by standard yaml parsers, it's already possible to use aliases for pipeline configs to reduce duplication. For example I can do something like this:
```yaml
test-win2008:
  resources:
    - win2008
  tasks:
    &test_tasks # define the whole task list as an alias
    - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "init"
    - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "build"
    - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "test"
test-win2012:
    resources:
      - win2012
    tasks: *test_tasks # use the previously defined alias
test-win7:
    resources:
      - win7
    tasks: *test_tasks # use the previously defined alias
```

So we use an alias to reuse the same list of tasks in multiple jobs running on different platforms.

This works well enough, but we are forced to define the alias the first time we use it somewhere in the yaml config where it is actually valid. This makes it harder to understand where aliases come from and more error prone to reorder sections in the config. It's also not possible, to my knowledge, to only define a part of a task list as an alias. In the above example, maybe I only want the first two `exec` tasks to be part of the alias, not the final one.

Therefore, I suggest supporting a dedicated `aliases` section like the one used on the [first example page](https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)).
That's currently not possible because the plugin will complain about an invalid key: 
> cd.go.plugin.config.yaml.YamlConfigException: aliases is invalid, expected pipelines or environments

Since the yaml parser takes care of resolving aliases, I reckon it wouldn't require many changes, besides dropping the aliases section after parsing as it's no longer needed.

**Comment by tomzo** [comment]
Hi @sandro-h 
I agree with most that you have said. 

> I suggest supporting a dedicated aliases section 

I am not sure if `aliases` is the best way to name it, but I agree about having such section.
Since user could be storing any part of configuration there, perhaps it should be called `partials` or `definitions`  or `common`?

I find this part especially common use case:
> .. maybe I only want the first two exec tasks to be part of the alias, not the final one.

I think that could be done if we first allow tasks to be **a list of (list or task)**. Then plugin could flatten list after parser resolves aliases. Something like this:
```yaml
test-win2008:
  resources:
    - win2008
  tasks:
    &test_tasks # define the whole task list as an alias
    - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "init"
    - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "build"
    - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "test"
test-win2012:
    resources:
      - win2012
    tasks: 
      - *test_tasks # use the previously defined alias
      - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "win12"
test-win7:
    resources:
      - win7
    tasks: 
      - exec:
        command: my_build_cmd.sh
        arguments:
          - "-DConfiguration=Release"
          - "pre-win7"
     - *test_tasks # use the previously defined alias
```
