### ISSUE TITLE
P4 material passwd exposed

### ISSUE THREAD

**Issue by gexgik** [tomzo/gocd-yaml-config-plugin#33]
Hi,

Is there a way to hide the password of the P4 materials? I've tried using the encrypted value and it seems that's not working.

Thanks,
George

**Comment by tomzo** [comment]
Hi @gexgik ,
Try using `encrypted_password` instead of `password` like so:
```
p4Material1:
  p4: "host.domain.com:12345"
  username: johndoe
  encrypted_password: YjIzNDM0MjM0bGEK
  use_tickets: false
  view: |
    //depot/external... //ws/external...
    //depot/tools... //ws/external...
  blacklist:
    - externals
    - tools
  auto_update: false
```

You can encrypt the raw value using [server API encryption endpoint](https://api.gocd.org/current/#encryption).

Let me know if that works. (It should, but I did not test it with actual p4 server)
