### ISSUE TITLE
Possibility to disable automatic scheduling

### ISSUE THREAD

**Issue by goeranu** [tomzo/gocd-yaml-config-plugin#36]
From what I can tell, there is no way to disable the automatic scheduling on new materials in a yaml configuration.  It would be nice if this could be added.

**Comment by tomzo** [comment]
Hi,

What do you mean by *automatic scheduling on new materials* ? Scheduling of newly added pipelines or material polling?

Automatic material updates cannot be disabled only for materials which are used as configuration repository. If you have configuration in other repository than material of pipeline then it is possible with ` auto_update: false`:
```
gitMaterial1:
  git: "http://my.git.repository.com"
  branch: feature12
  blacklist:
    - externals/**/*.*
    - tools/**/*.*
  destination: dir1
  auto_update: false
  shallow_clone: true
```
