### ISSUE TITLE
Pipeline sorting or order mismatch from yaml file

### ISSUE THREAD

**Issue by mribichich** [tomzo/gocd-yaml-config-plugin#4]
Hi there, I'm starting using plugin. I have gocd 16.8.0 and plugin 0.2.0, and my pipelines are being sort in a weird way in the dashboard.

I have 3 repos with yaml configs, and one of them is sort ok: First, Second, Third, the other one is: First, Third, Second and the last one is complete backwards: Third, Second, First.

The yaml's are in the right order.

Is there a way to fix this?

Here is an example of the files, all 3 look the same:

```
pipelines:
  build_pipeline:
    group: groupA
    label_template: ...
    materials:
      svn_material:
        svn: ...
    stages:
      - build:
          approval: success
          fetch_materials: yes
          clean_workspace: true
          jobs:
            build:
              tasks:
                - plugin:
                    run_if: passed
                    options:
                      script: ...
                    configuration:
                      id: script-executor
                      version: 1
              artifacts:
                - build:
                    source: "*"
                    destination: all

  beta_pipeline:
    group: groupA
    label_template: "${build_pipeline}"
    locking: false
    environment_variables:
      ...
    secure_variables:
      ...
    materials:
      build_pipeline:
        pipeline: build_pipeline
        stage: build
    stages:
      - beta:
          approval: success
          fetch_materials: yes
          clean_workspace: true
          jobs:
            beta:
              tasks:
                - fetch:
                    run_if: passed
                    pipeline: build_pipeline
                    stage: build
                    job: build
                    is_file: no
                    source: all
                    destination: build_pipeline
                - plugin:
                    run_if: passed
                    options:
                      script: ...
                    configuration:
                      id: script-executor
                      version: 1
              artifacts:
                - build:
                    source: dist/*.zip
                    destination: dist

  release_pipeline:
    group: groupA
    label_template: "${build_pipeline}"
    locking: false
    environment_variables:
      ...
    secure_variables:
      ...
    materials:
      build_pipeline:
        pipeline: build_pipeline
        stage: build
      beta_pipeline:
        pipeline: beta_pipeline
        stage: beta
    stages:
      - release:
          approval: manual
          fetch_materials: yes
          clean_workspace: true
          jobs:
            release:
              tasks:
                - fetch:
                    run_if: passed
                    pipeline: build_pipeline
                    stage: build
                    job: build
                    is_file: no
                    source: all
                    destination: build_pipeline
                - fetch:
                    run_if: passed
                    pipeline: beta_pipeline
                    stage: beta
                    job: beta
                    is_file: no
                    source: dist
                    destination: beta_pipeline
                - plugin:
                    run_if: passed
                    options:
                      script: ...
                    configuration:
                      id: script-executor
                      version: 1
```

thanks!
