### ISSUE TITLE
Whitelist does not work if pipeline has an upstream pipeline as material

### ISSUE THREAD

**Issue by rkrisztian** [tomzo/gocd-yaml-config-plugin#50]
In a nutshell I have this config:

```
pipelines:
  p1:
    materials:
      my-repo:
        git: some-url
        auto_update: true
    stages:
      # (...)
  p2:
    materials:
      my-repo:
        git: some-url
        whitelist:
          - some-dir/**/*
        auto_update: true
      p1-as-upstream:
        pipeline: p1
        stage: some-stage
```

Now if I commit something outside of `some-dir`, I expect `p2` not triggered, but it does, both pipelines are built. That sounds wrong. The whitelisting works fine if I remove `p1-as-upstream` from the `p2` materials.

Do you know why it is not working? Is it a YAML config plugin bug or a GoCD bug?

**Comment by tomzo** [comment]
You'll have to be more specific about what are your expectations. Could you elaborate a bit?
But from what I see above, that is expected behavior, when you push to my-repo, it triggers p1 (because there is no whitelist there), and then **p1 triggers p2** because it is a material of p2. This is justified by the logic that if project in p2 somehow depends on p1 then a new build in p1 could break something in p2, hence you should build p2 with new p1. Is that clear enough?

**Comment by rkrisztian** [comment]
You're right, my example is a bit off, so I'm going to provide a slightly different use case with more detail. I will need to test it in a short PoC though, to confirm that it's still a bug.

In my case `my-repo` is a repository containing 3 projects:

* `pr1` as a library project (built by pipeline `p1`).
* `pr2` and `pr3` as end-user projects, both depending on `pr1`. (`pr2` is built by `p2`, and `pr3` is built by `p3`, configured similarly to `p2`. Both pipelines use the artifact generated by `p1`.)

Now, If only `pr3` changed, then I don't want to build `pr2`, and if I only `pr2` changed, I don't want to build `pr3`. For that I can add a **blacklist** that ignores `pr3` in `p2`, and `pr2` in `p3`.

So in my case, I am sure that changes in `p3` will not break `p2`, and changes in `p2` will not break `p1`.

=> As promised, I will return with a confirmed example.

**Comment by tomzo** [comment]
There is one minor bug that I am aware of. If you are introducing whitelist/blacklist change in current commit `123`, then this will not apply to builds triggered by it. Meaning `123` will trigger pipelines using old rules. But every next build should respect filters. Be aware of this when you confirm this bug.

**Comment by rkrisztian** [comment]
Thanks. It **still does not work** the way I expect. Here is my config:

```
pipelines:
  p1:
    materials:
      my-repo:
        git: some-url
        auto_update: true
  p2:
    materials:
      my-repo:
        git: some-url
        blacklist:
          - pr3/**/*
        auto_update: true
      p1-as-upstream:
        pipeline: p1
        stage: some-stage
  p3:
    materials:
      my-repo:
        git: some-url
        blacklist:
          - pr2/**/*
        auto_update: true
      p1-as-upstream:
        pipeline: p1
        stage: some-stage
```

Then, if make a change inside `pr3`, the `p2` pipeline is still triggered. I also retested with `pr2` changes, expecting no triggering of `p3`, but it did. => Not OK.

If I removed `p1-as-upstream` from the material config of `p2`, then changes in `pr3` did not trigger `pr2`, which is OK.

=> It's like whitelists/blacklists are ignored when upstream pipelines are used.
