### ISSUE TITLE
generic java.lang.String cannot be cast to java.util.Map failure

### ISSUE THREAD

**Issue by tedder** [tomzo/gocd-yaml-config-plugin#54]
there's some dumb issue that's preventing me from getting an MVP working. Here's the error:

```
Parsing configuration repository using Plugin yaml.config.plugin failed for material: URL: git@github.my/repo.git, Branch: master [Dec-01 22:50:02]
codebuild/provisioning.gocd.yml; - Failed to parse pipeline provisioning; java.lang.String cannot be cast to java.util.Map
```

And the yaml mentioned:

```
---
format_version: 1
pipelines:
  provisioning:
    group: ops
    materials:
      provisioning:
        git: 'git@github.my/repo.git'
    stages:
    - build:
      jobs:
        hello:
          tasks:
          - exec:
            command: env
```

That's pretty minimal! It passes yamllint, and this plugin doesn't help me with which parameter is wrong, except that it's somewhere inside my pipeline.

**Comment by tomzo** [comment]
Hi,
Yeah, errors are not always too friendly. 
The ident is wrong.

Try this
```
---
format_version: 1
pipelines:
  provisioning:
    group: ops
    materials:
      provisioning:
        git: 'git@github.my/repo.git'
    stages:
     - build:
        jobs:
          hello:
            tasks:
             - exec:
                command: env
```

The rule of thumb is that hashes are always done like this:
```
key:
  a: 1
  b: something
```
Never all in same level like so
```
key:
a: 1
b: something
```
