### ISSUE TITLE
Support YAML merge syntax

### ISSUE THREAD

**Issue by michaelbannister** [tomzo/gocd-yaml-config-plugin#55]
On the back of the handy 'common' section introduced in #32, it would be really handy if this plugin supported the [YAML merge key](http://yaml.org/type/merge.html), like this:
```yaml
common:
  material_yaml_config_plugin: &material_yaml_config_plugin
    git: git@github.com:tomzo/gocd-yaml-config-plugin.git
    auto_update: false
  material_gocd:
    git: git@github.com:gocd/gocd.git
    auto_update: false
    blacklist:
      - externals/**/*.*

pipelines:
  a_pipeline:
  materials:
    yaml_config_plugin:
      <<: *material_yaml_config_plugin
      destination: yaml_config_plugin
    gocd:
      <<: *material_gocd
      destination: gocd
```
I had a look at yamlbeans recently and it seems it now has support for this, but a release has not been made since then. https://github.com/EsotericSoftware/yamlbeans/commit/095d83d
