### ISSUE TITLE
whitelist is not working

### ISSUE THREAD

**Issue by shomodj** [tomzo/gocd-yaml-config-plugin#61]
invert_filter is not set to true when using whitelist, there is no mention it in the code

**Comment by tomzo** [comment]
You can see how to use whitelist [under here](https://github.com/tomzo/gocd-yaml-config-plugin#git). You either specify `whitelist` or `blacklist`. 

What do you mean by ?
> invert_filter is not set to true when using whitelist

How did you configure pipeline material? What do you expect from whitelist.

**Comment by shomodj** [comment]
gocd version: 17.12.0
material type: hg

```  
image_nexus:
    group: images
    materials:
      xxx:
        hg: ssh://hg@bitbucket.org/xxx
        whitelist:
          - images/nexus/**/*
```

curl to get pipeline settings
```
  "materials": [
    {
      "type": "hg",
      "attributes": {
        "url": "ssh://hg@bitbucket.org/xxx",
        "destination": null,
        "filter": {
          "ignore": [
            "images/nexus/**/*"
          ]
        },
        "invert_filter": false,
        "name": "xxx",
        "auto_update": true
      }
    }
  ],
```

now lets try blacklist
```
  image_nexus:
    group: images
    materials:
      xxx:
        hg: ssh://hg@bitbucket.org/xxx
        blacklist:
          - images/nexus/**/*
```

curl
```
  "materials": [
    {
      "type": "hg",
      "attributes": {
        "url": "ssh://hg@bitbucket.org/xxx",
        "destination": null,
        "filter": {
          "ignore": [
            "images/nexus/**/*"
          ]
        },
        "invert_filter": false,
        "name": "xxx",
        "auto_update": true
      }
    }
  ],
```

on whitelist, invert_filter should be true, I have tried the same setup manually using UI and it works as expected, I have a bunch of docker images and they all rebuild even if I change only one, whitelist should prevent this
