### ISSUE TITLE
runtime error when using yaml anchor <<:

### ISSUE THREAD

**Issue by vaibhavparnalia** [tomzo/gocd-yaml-config-plugin#63]
![image](https://user-images.githubusercontent.com/7274550/35888351-29791c64-0b4c-11e8-9f1c-bdbea7b32e71.png)
runtime; - Unexpected error when handling plugin response java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/7274550/35888787-de7decec-0b4d-11e8-8734-eecb0e823fef.png)

deploy-dev: &deploy_pipeline
    group: aws
    materials: &deploy_pipeline_materials
      git-a: *baybridge
      git-bb: *baybridge-apps
      create-ami:
        pipeline: initialize
        stage: xxx
deploy-qa:
    group: aws
    materials:
      <<: *deploy_pipeline_materials
      deploy-dev:
        pipeline: deploy-dev
        stage: xxx

**Comment by shrykull** [comment]
I got pretty much the same problem condensed on a slightly smaller config. any updates?

```
common:
  default_environment: &default_environment
    ANSIBLE_ACDC_TOMCAT_PROTOCOL: https
pipelines:
  myPipeline:
    environment_variables:
      <<: *default_environment
      ANSIBLE_TOMCAT_PORT: 10443
```

The error reads `Failed to parse pipeline myPipeline; java.util.HashMap cannot be cast to java.lang.String`
