### ISSUE TITLE
Change pipeline environment fail

### ISSUE THREAD

**Issue by DavidUser** [tomzo/gocd-yaml-config-plugin#67]
I had the following environment:
```
environment:
  Prod:
    pipelines:
      - sample-pipeline-site0
      - sample-pipeline-site1
```
When I want change site1 to environment Prod-datacenter2 is expected just change the configuration to:
```
environment:
  Prod:
    pipelines:
      - sample-pipeline-site0
  Prod-datacenter2:
    pipelines:
      - sample-pipeline-site1
```

But just that not change the environment. I need before complete remove the pipeline definition.
```
environment:
  Prod:
    pipelines:
      - sample-pipeline-site0
```
