### ISSUE TITLE
Missing field 'package_id'

### ISSUE THREAD

**Issue by nudgegoonies** [tomzo/gocd-yaml-config-plugin#70]
Hi,
we want to switch from JSON to YAML piplines as code. I have the following example which is an extract of our pipeline:
```
    materials:
      webapp:
        package_id: 111-222-333-444
        type: package
      webapp_appcfg:
        package_id: 555-666-777-888
        type: package
```
This gives the following error:
```
deployment.yml; Pipeline deployment; Package material webapp ID: unknown; - Missing field 'package_id'
deployment.yml; Pipeline deployment.; Package material webapp_appcfg ID: unknown; - Missing field 'package_id'
```
In the original JSON pipeline that worked looked like this:
```
  "materials": [
    {
      "package_id": "111-222-333-444",
      "type": "package",
      "name": "webapp"
    },
    {
      "package_id": "555-666-777-888",
      "type": "package",
      "name": "webapp_appcfg"
    }
  ],
```
I also tried this, which is the output of the json to yaml converter, and it resulted in the same error:
```
materials:
- package_id: 111-222-333-444"
  type: package
  name: webapp
- package_id: 555-666-777-888
  type: package
  name: webapp_appcfg
```
Any ideas what's going wrong?
Kind regards,
Andreas
