### ISSUE TITLE
Fan-in doesn't work

### ISSUE THREAD

**Issue by Leopard2A5** [tomzo/gocd-yaml-config-plugin#8]
The example pipeline in this repository https://gitlab.com/leopard2a5-knorke/example-pipelines-yaml defines a simple fan-out and then a fan-in. However the fan-in doesn't work, only one reference is created between the two "source"-pipelines and the final "target"-pipeline. When i create the same thing in json it works.

**Comment by tomzo** [comment]
Hi,
Your example does not work, because you have defined 2 materials with same name:
```yaml
      upstream:
        name: pipeline-unit-test
        type: dependency
        pipeline: pipeline-unit-test
        stage: unit-test
      upstream:
        name: pipeline-integration-test
        type: dependency
        pipeline: pipeline-integration-test
        stage: integration-test
```

`upstream` is **material name**, not type. Syntax in YAML is a bit different than in JSON. 
The plugin silently ignores second material when you make this kind of error, see #3

To fix your problem, rename materials to something like:
```yaml
      unit:
        name: pipeline-unit-test
        type: dependency
        pipeline: pipeline-unit-test
        stage: unit-test
      integration:
        name: pipeline-integration-test
        type: dependency
        pipeline: pipeline-integration-test
        stage: integration-test
```

Also ` type: dependency` is not required, in YAML
