### ISSUE TITLE
empty secure_variables treated as environment_variables - secrets exposed in log files

### ISSUE THREAD

**Issue by birchb1024** [tomzo/gocd-yaml-config-plugin#84]
With a pipeline defined such as this:

```
# format_version: 2
pipelines:
  MyPipeline:
    label_template: ${COUNT}
    group: MyGroup
    materials:
        shared:
          git: ssh://git@bitbucket:79/somerepo.git
    environment_variables:
      DUMMY: "Tigers"
    secure_variables:
      MYSECRET: ""
    stages:
        - MyStage_etc

```
** Observed Behavior:

When the pipeline is instantiated, and the user selects 'Trigger with options' the MYSECRET variable is collected in a normal insecure variable instead of as a secure variable. After execution is complete, the MYSECRET variable value is printed in the log file instead of being redacted with asterisks ******.

** Expected
The desired behaviour is that an empty secure_variable is handled in the 'Secure Variables' tab of the Trigger dialog. Also the value of the variable should be redacted in the log file. Also, the pipeline should not throw an error if the initial value in the YAML is the empty string.  

With: GoCD Version 18.5.0
