### ISSUE TITLE
Pipeline definition with stages alias and additional stages

### ISSUE THREAD

**Issue by magowant** [tomzo/gocd-yaml-config-plugin#95]
In a similar way to a tasks alias can be mixed in with additional tasks (https://github.com/tomzo/gocd-yaml-config-plugin#yaml-aliases), add the ability to do the same with stages:

``` yaml
common:
  stages: &stages
    - stage1:
      - tasks:
        ...
    - stage2:
      - tasks:
        ...

pipelines:
  - pipeline1:
      stages: *stages

  - pipeline2:
      stages:
      - *stages
      - stage3:
        - tasks:
          ...
```
